### ISSUE TITLE
ROS2: High CPU load of python scripts

### ISSUE THREAD

**Issue by erblinium** [ensenso/ros_driver#105]
Getting the following error:
`[ERROR] [ensenso_camera_node-10]: process has died [pid 17673, exit code -9`
when running the `ensenso_camera_node` with a virtual camera and virtual objects. It crashes after around ~300-350 seconds.

**Comment by erblinium** [comment]
Is looks like it is a memory problem. The memory of the `ensenso_camera_node` always increases until it crashes with the error code. The virtual camera also disappears from NxView after the crash, and I have to restart machine to get it back.

**Comment by erblinium** [comment]
Investigating further I see that I have another node running of type `image_stream` in the `ensenso_camera` package. This node's CPU usage increases as the nodes run.

**Comment by erblinium** [comment]
Any ideas what might cause this @benthie? I believe it has to do with the requested data from the `image_stream` node...

**Comment by benthie** [comment]
I will have a look at it.
- Are you using ROS1 or ROS2?
- Are you using the virtual camera directly or as a file camera?

Let me summarize what you are doing: you have an `ensenso_camera_node` running and besides that only the `image_stream` script?

**Comment by erblinium** [comment]
> I will have a look at it.
> 
>     * Are you using ROS1 or ROS2?
ROS2
> 
>     * Are you using the virtual camera directly or as a file camera?
Virtual camera directly
> 
> 
> Let me summarize what you are doing: you have an `ensenso_camera_node` running and besides that only the `image_stream` script?
Yes, I start them both from a launch file. I also have some other nodes running TF, robot state publishers, but I do not think they cause any problems here.

**Comment by benthie** [comment]
Thank you for the details. I will get back to you if I have found something .

**Comment by benthie** [comment]
Which Ensenso SDK version do you use?

**Comment by erblinium** [comment]
> Which Ensenso SDK version do you use?

3.3.1417

**Comment by benthie** [comment]
I think I found a solution for the high CPU load of the python scripts. The fix is to use a `MultiThreadedExecutor` in combination with a `ReentrantCallbackGroup`. I am currently testing it on my machine and it looks good with regard to the CPU usage. For the memory leak I created a separate [issue](#107). I will keep you posted as soon as I have a working fix that also passes all tests.

**Comment by benthie** [comment]
FYI, the fixes for both this issue and https://github.com/ensenso/ros_driver/issues/107 are part of the currently released [v2.1.0](https://github.com/ensenso/ros_driver/releases/tag/v2.1.0).
