### ISSUE TITLE
Ensenso shown as available but cannot be opened

### ISSUE THREAD

**Issue by ttyusb007** [ensenso/ros_driver#110]
This is not related to ROS, but don't know a better place to raise the question.

I have several ensensos on the station, after a fresh system installation and configuration of network port, all my sensors appear to be available when I open nxView, however, if I try to open any of the camera it will hang there for a long time with CaptureTimeout and eventually show an error message saying ComputeDisparityMap: CommandComputeDisparityMap: Camera has invalid piped model.

I have never seen this error before, could you point me to what are some possible causes? Thanks!

**Comment by saierd** [comment]
Hi, please contact the support of IDS, our distributor on https://en.ids-imaging.com/support.html. They will help you to analyze the problem.
