### ISSUE TITLE
CMake cant find Ensenso SDK

### ISSUE THREAD

**Issue by belalhmedan90** [ensenso/ros_driver#117]
Hi, 
I have installed Ensenso SDK on Ubuntu 20.04; apt list shows: `ensenso-sdk/now 3.5.1419 amd64 [installed,local]`
when I try to build the catkin workspace I get the following error: 
```
CMake Error at CMakeLists.txt:68 (message):
  Please install the Ensenso SDK

Failed     << ensenso_camera:cmake 
```
can you please tell me how can I resolve this issue? thanks in advance.

**Comment by benthie** [comment]
Did you set the `ENSENSO_INSTALL` environment variable? It is described [here](https://www.ensenso.com/manual/3.5/about/installation.html) under **Storage of Settings**.

**Comment by belalhmedan90** [comment]
@benthie thanks, `export ENSENSO_INSTALL=/opt/ensenso` solved the problem in my case.
