### ISSUE TITLE
registerd images resolution

### ISSUE THREAD

**Issue by belalhmedan90** [ensenso/ros_driver#126]
I can't find any parameter in the [launch files](https://github.com/ensenso/ros_driver/tree/master/ensenso_camera/launch) to change image resolution, is there any option flag to adjust resolution? `1280*720` or `640*480`

**Comment by benthie** [comment]
See [this tutorial](http://wiki.ros.org/ensenso_driver/Tutorials/Parameters) for a guide on how to set your camera parameters.

Let me know if you have further questions.
