### ISSUE TITLE
8UC1 provided need mono8

### ISSUE THREAD

**Issue by tabelh** [ensenso/ros_driver#17]
Hello I am trying to use this driver for the ensenso camera, the package that i intend to use it with accepts mono8 encoding, however, the camera provides 8UC1. Is this something that can be altered? I have been looking for conversion methods but that does not seem to be possible as 8UC1 is not a color format. I am subscribing to the /rectified/left/image topic. Would I need to use a different one? Or do you perhaps know of a method to convert the data?

Thanks in advance!

**Comment by saierd** [comment]
The two formats are equivalent and contain the same data. It seems like mono8 is more popular in ROS, though (see e.g. intel-ros/realsense#253), so I changed it.
