### ISSUE TITLE
Consider not using 'map' as the default frame

### ISSUE THREAD

**Issue by gavanderhoorn** [ensenso/ros_driver#2]
`map` is really more typically used with mobile robots to provide a reference for a global frame that associated with a map. See also [REP-105: Coordinate Frames for Mobile Platforms - map](http://www.ros.org/reps/rep-0105.html#map).

It *is* the default frame that RViz starts with, but this is typically worked around by either providing a custom RViz config file that already uses a different frame, or by documenting the steps needed to change the *Fixed Frame*. Another option is to use the `-f` or `--fixed-frame` command line option, which should allow you to specificy a frame while starting RViz.

To be more in-line with other ROS camera drivers, perhaps `${prefix}_rgb_optical_frame` and `${prefix}_(ir|depth)_optical_frame` (as needed) might be more appropriate for the sensor locations, and `camera_link` for the base frame of the entire camera (this of course depends on the frames that are actually needed for the different parts of the physical device).

**Comment by saierd** [comment]
I changed it to "ensenso_optical_frame" now. We only have a single frame for the camera images and the point cloud, so I guess that is a reasonable name that is similar to what other cameras use.

**Comment by gavanderhoorn** [comment]
Hm. Would it perhaps make sense to include the two frames anyway, but put an identity transform between them?

That would make it compatible to a lot of other depth sensors in ROS, while still modelling the fact that you only have a single frame.

**Comment by gavanderhoorn** [comment]
Related: would you consider providing a `ensenso_description` (or `ensenso_support`, depending on how many products you intend to support) in combination with the driver?

That would allow you to standardise these frame/link names easily in a urdf, and remove the burden of modelling the camera from your users.

**Comment by gavanderhoorn** [comment]
Captured this in #3.
