### ISSUE TITLE
Line-ending issue in camera.cpp?

### ISSUE THREAD

**Issue by gavanderhoorn** [ensenso/ros_driver#33]
Not sure whether it was intentional, but c549c808 seems to have done some bad things with the line-endings in `ensenso_camera/src/camera.cpp`.

**Comment by gavanderhoorn** [comment]
Related: would there be interest in setting up some form of CI in this repository?

**Comment by yguenduez** [comment]
Thanks for the hint! The line ending was not intended. And 

> interest in setting up some form of CI in this repository?

Of Couse. This is probably the next thing to do.

**Comment by gavanderhoorn** [comment]
> > interest in setting up some form of CI in this repository?
> 
> Of Couse. This is probably the next thing to do.

Could I suggest using [industrial_ci](https://github.com/ros-industrial/industrial_ci) for this?

The only 'difficult' bit would be the sdk, but seeing as you are maintaining that yourself, it should be more than possible to configure things such that it can be installed into the container before performing the rest of the build.

If using `industrial_ci`, I'd recommend using the [master branch](https://github.com/ros-industrial/industrial_ci/tree/master), as it's received quite a bit of attention since `legacy`.

**Comment by yguenduez** [comment]
Thanks! I will have definitely have a look into it. And ..
..how do you respond that fast? :)

**Comment by gavanderhoorn** [comment]
Github has had email notifications for quite a while now ;)

**Comment by gavanderhoorn** [comment]
Perhaps @ipa-mdl could comment on what the best/most efficient way would be to get a non-`apt`/non-ROS/non-`rosdep`pable pkg dependency injected into an `industrial_ci` Travis setup.

**Comment by gavanderhoorn** [comment]
See #34 for a proposed CI configuration.
