### ISSUE TITLE
How to compute the Pointcloud from disparity image?

### ISSUE THREAD

**Issue by NikolasE** [ensenso/ros_driver#4]
I want to store the 3d data for later processing and would like to only store the disparity image (together with some camera matrix) to only store the minimal amount of data and not the full cloud. Which Information do I have to store and how can I later compute the cloud?

**Comment by saierd** [comment]
In the NxLib, you can project disparities to 3D with the [Reprojection](https://www.ensenso.com/manual/index.html?_cameras_byserialno_$stereoserial_calibration_dynamic_stereo_reprojection.htm) matrix. Unfortunately there is currently no good way of getting that matrix from the ROS node. The CameraInfo message does not contain it.

You can use the [StereoModel](http://docs.ros.org/lunar/api/image_geometry/html/c++/classimage__geometry_1_1StereoCameraModel.html) class, though. It can compute this matrix from the two camera infos and also provides a method for reprojecting the disparity image.
