### ISSUE TITLE
Camera publishes data in wrong frame if TF Lookup failed

### ISSUE THREAD

**Issue by NikolasE** [ensenso/ros_driver#5]
If the target_frame is set to a frame that is not in the tree, the cloud is published anyway and only a warning is printed ("Could not get the transformation to the target frame from TF. Using an identity transformation for this frame."). 

If the camera is misconfigured, there should be no output at all. With the current implementation, every subscriber would assume that the data was transformed into the frame (as it is set in the header), so that next robot movements will rely on wrong data. Just ignoring the failed tf-lookup and publishing wrong data is the worst case for a camera, especially if the data is used for collision avoidance. 

If data is published, the frame should be set to the camera_frame, so that a listener has a chance to notice there was a problem. 

Same for writePoseToNxLib: If something is wrong with the pose, Identity is used and not even a return value is given.

**Comment by saierd** [comment]
Makes sense. TF exceptions now cancel all actions and their message gets returned in the action's error field.
