### ISSUE TITLE
A question about segmentation fault (core dumped)

### ISSUE THREAD

**Issue by shenjiyuan123** [ensenso/ros_driver#73]
I met the problem about segmentation fault when I run this `rosrun ensenso_camera ensenso_camera_node`
The result is like below:
`~/ensenso_ros1_ws$ rosrun ensenso_camera ensenso_camera_node
[ INFO] [1644395246.946467651]: Initializing nodelet with 12 worker threads.
Segmentation fault (core dumped)
`

Environment:
- ubuntu 20.04
- ensenso  s10
- sdk 3.2.489
- ros noetic

Thanks!

**Comment by saierd** [comment]
Do you run the latest commit 0e6822103b1f495105139d4a1e938546a2054159, which added support for S-series cameras?

If so, where exactly does it crash? Can you build a debug version of the driver and post the stack trace?

**Comment by shenjiyuan123** [comment]
Thanks, I have found the reason. I can use roslaunch to start the topic instead.
