### ISSUE TITLE
Failed to load nodelet /mono/Ensenso_

### ISSUE THREAD

**Issue by dilerbatu** [ensenso/ros_driver#89]
Hi Everyone, 
I have ensenso S series camera and I already installed nxView and I can see my view. I am trying to connect with ROS. I downloaded the repository and built it. When I run 

roslaunch ensenso_camera register_depth_image.launch 

or

roslaunch ensenso_camera nodelet.launch

 it gives this error:

![Screenshot from 2022-07-19 13-43-46](https://user-images.githubusercontent.com/71350258/179748920-5284192a-17e0-4770-b265-8c57cb6a5b6f.png)

Thank you !

**Comment by saierd** [comment]
It seems like something crashed with a segmentation fault, but from the error message it is not clear, whether it was the nodelet manager, one of the camera nodes or the NxLib.

- Do you have the [version 1.7](https://github.com/ensenso/ros_driver/releases/tag/v1.7.0) or later, which added support for the S-series in the ROS interface?
- Do the camera nodes run individually if you simply rosrun `ensenso_camera_node`?
- Can you post the content of the log files, which are mentioned in the error message?

**Comment by saierd** [comment]
I will close this for now. Feel free to reopen if the issue persists and you have further information.
