### ISSUE TITLE
Can i use this package for X36-BL?

### ISSUE THREAD

**Issue by fwarmuth** [ensenso/ros_driver#98]
Hey,
has anyone tried this driver with an X36-BL system?
Does a ROS driver for X36 system exists, when yes, where can I find it?

Regards

**Comment by benthie** [comment]
Yes, the driver supports all of our Ensenso cameras. We even provide xacros and STL files [here](https://github.com/ensenso/ros_driver/tree/master/ensenso_description)

**Comment by fwarmuth** [comment]
Thanks!
